from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

def create_pdf(filename):
    doc = SimpleDocTemplate(filename, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='TitleStyle', fontSize=16, leading=20, spaceAfter=10, fontName='Helvetica-Bold', alignment=1))
    styles.add(ParagraphStyle(name='SubtitleStyle', fontSize=12, leading=16, spaceAfter=20, alignment=1))
    styles.add(ParagraphStyle(name='CustomHeading1', fontSize=14, leading=18, spaceBefore=15, spaceAfter=10, fontName='Helvetica-Bold'))
    styles.add(ParagraphStyle(name='NormalStyle', fontSize=11, leading=15, spaceAfter=8))
    
    Story = []
    
    # Title
    Story.append(Paragraph("Milestone 2: Data Collection and Preprocessing", styles['TitleStyle']))
    Story.append(Paragraph("Automated Creative Writing Evaluation - Project Draft #1", styles['SubtitleStyle']))
    Story.append(Paragraph("<b>Members:</b> Theo Helton, David Pope, Steven Weil", styles['SubtitleStyle']))
    
    # Section 1
    Story.append(Paragraph("1. Project Motivation and Goal", styles['CustomHeading1']))
    text1 = "As artificial intelligence (AI) text generation becomes widespread, identifying how large language models (LLMs) compare to human creativity is increasingly critical. Current models excel at technical and informational tasks, but their creative writing capabilities are often perceived as lacking. The goal of this project is to develop a deep learning neural network, trained exclusively on human-written fiction, that can ingest a piece of writing and evaluate its creativity based on a deterministic five-dimension rubric. We will then use this model to score and compare stories generated by modern LLMs (ChatGPT, Claude, Gemini, Perplexity, Copilot) to see which models best mimic human creative expression."
    Story.append(Paragraph(text1, styles['NormalStyle']))
    
    Story.append(Spacer(1, 0.1 * inch))
    
    # Section 2
    Story.append(Paragraph("2. Project Workflow / Framework", styles['CustomHeading1']))
    text2 = "The project will follow a systematic pipeline:"
    Story.append(Paragraph(text2, styles['NormalStyle']))
    
    workflow_items = [
        "<b>Data Collection & Preprocessing:</b> Acquire the raw dataset, clean out noise (URLs, markdown), and filter out unusable instances.",
        "<b>Rubric Pipeline Execution:</b> Score the entire human-written dataset using our automated rubric consisting of Lexical Richness, Syntactic Complexity, Novelty, Imagery, and Narrative Dynamics.",
        "<b>Model Training:</b> Train a baseline Multi-Layer Perceptron (MLP) on the extracted features, followed by fine-tuning a RoBERTa transformer on the raw human text.",
        "<b>AI Evaluation:</b> Generate counterpart stories using modern LLMs and run them through the fine-tuned RoBERTa model.",
        "<b>Analysis / Visualization:</b> Compare score distributions across the different LLMs."
    ]
    
    list_items = [ListItem(Paragraph(item, styles['NormalStyle'])) for item in workflow_items]
    Story.append(ListFlowable(list_items, bulletType='bullet', start='bulletchar'))

    Story.append(Spacer(1, 0.1 * inch))
    
    # Section 3
    Story.append(Paragraph("3. Dataset Description and Analysis", styles['CustomHeading1']))
    text3 = "We are using the <b>Reddit WritingPrompts (FAIR)</b> dataset, an established dataset for hierarchical story generation consisting of prompt-story pairs sourced from the r/WritingPrompts subreddit."
    Story.append(Paragraph(text3, styles['NormalStyle']))
    
    text4 = "<b>Exploratory Data Analysis (EDA):</b> We successfully downloaded the full <i>train</i> split of the dataset, consisting of <b>272,600 human-written stories</b>. Our analysis indicates that the dataset is highly robust for our goal of evaluating short fiction (approx. 500 words)."
    Story.append(Paragraph(text4, styles['NormalStyle']))
    
    eda_items = [
        "<b>Mean Story Length:</b> 551 words",
        "<b>Median Story Length:</b> 452 words",
        "<b>Format:</b> Standardized text matched directly to an inspirational prompt."
    ]
    list_items_eda = [ListItem(Paragraph(item, styles['NormalStyle'])) for item in eda_items]
    Story.append(ListFlowable(list_items_eda, bulletType='bullet', start='bulletchar'))

    Story.append(Spacer(1, 0.1 * inch))
    
    # Section 4
    Story.append(Paragraph("4. Preprocessing Steps", styles['CustomHeading1']))
    text5 = "Our preprocessing pipeline, built using Python and Pandas, reads the raw parquet files and executes the following sequence:"
    Story.append(Paragraph(text5, styles['NormalStyle']))

    prep_items = [
        "<b>URL Removal:</b> Standard regex patterns are used to strip stray links and URIs.",
        "<b>Markdown & Artifact Removal:</b> Bold, italics, and blockquote formatting tokens are removed to prevent models from overfitting on Reddit syntax. We also strip structural tags like [ WP ] (Writing Prompt) and [ EU ] (Established Universe).",
        "<b>Length Filtering:</b> Any story containing fewer than 100 words is dropped from the dataset (typically broken or incomplete submissions). From our initial 272,600 samples, only 21 were removed, resulting in a finalized clean training dataset of <b>272,579</b> stories."
    ]
    list_items_prep = [ListItem(Paragraph(item, styles['NormalStyle'])) for item in prep_items]
    Story.append(ListFlowable(list_items_prep, bulletType='bullet', start='bulletchar'))
    
    Story.append(Spacer(1, 0.1 * inch))
    
    # Section 5
    Story.append(Paragraph("5. Key References", styles['CustomHeading1']))
    ref_items = [
        "<b>Dataset:</b> Fan, A., Lewis, M., & Dauphin, Y. (2018). <i>Hierarchical Neural Story Generation</i>. FAIR WritingPrompts Dataset. Accessible via Hugging Face.",
        "<b>Libraries utilized:</b> Hugging Face datasets, pandas, spacy, NLTK, and vaderSentiment."
    ]
    list_items_ref = [ListItem(Paragraph(item, styles['NormalStyle'])) for item in ref_items]
    Story.append(ListFlowable(list_items_ref, bulletType='bullet', start='bulletchar'))

    # Build PDF
    doc.build(Story)
    
if __name__ == "__main__":
    create_pdf("/Users/theoh/Documents/Development/CSC426/AICreativityJudge/Docs/Milestone_2_Draft.pdf")
    print("PDF successfully generated.")
